version: '2'
services:
  skpdynamicapplication-app:
    image: skpdynamicapplication
    environment:
      - _JAVA_OPTIONS=-Xmx512m -Xms256m
      - SPRING_PROFILES_ACTIVE=prod,swagger
      - MANAGEMENT_METRICS_EXPORT_PROMETHEUS_ENABLED=true
      - SPRING_DATASOURCE_URL=jdbc:mysql://skpdynamicapplication-mysql:3306/skpdynamicapplication?useUnicode=true&characterEncoding=utf8&useSSL=false&createDatabaseIfNotExist=true
      - JHIPSTER_SLEEP=30 # gives time for other services to boot before the application
      - SPRING_DATA_JEST_URI=http://skpdynamicapplication-elasticsearch:9200
      - SPRING_ELASTICSEARCH_REST_URIS=http://skpdynamicapplication-elasticsearch:9200
    ports:
      - 8080:8080
  skpdynamicapplication-mysql:
    extends:
      file: mysql.yml
      service: skpdynamicapplication-mysql
  skpdynamicapplication-elasticsearch:
    extends:
      file: elasticsearch.yml
      service: skpdynamicapplication-elasticsearch
